<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" Version="0.3.0-preview.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerShell.DependencyInjection\PowerShell.DependencyInjection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ModelContextProtocol.Pwsh.psd1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
